# Generated by Django 4.0.3 on 2022-03-25 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Msg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender', models.CharField(default='', max_length=250)),
                ('text', models.TextField(default='')),
                ('date', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
